/*
dhtmlxScheduler.Net v.3.1.2 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e.config.container_autoresize=!0,e.config.month_day_min_height=90;var t=e._pre_render_events;e._pre_render_events=function(i,s){if(!e.config.container_autoresize)return t.apply(this,arguments);var n=this.xy.bar_height,a=this._colsS.heights,r=this._colsS.heights=[0,0,0,0,0,0,0],d=this._els.dhx_cal_data[0];if(i=this._table_view?this._pre_render_events_table(i,s):this._pre_render_events_line(i,s),this._table_view)if(s)this._colsS.heights=a;else{var o=d.firstChild;
if(o.rows){for(var l=0;l<o.rows.length;l++){if(r[l]++,r[l]*n>this._colsS.height-this.xy.month_head_height){var _=o.rows[l].cells,h=this._colsS.height-this.xy.month_head_height;1*this.config.max_month_events!==this.config.max_month_events||r[l]<=this.config.max_month_events?h=r[l]*n:(this.config.max_month_events+1)*n>this._colsS.height-this.xy.month_head_height&&(h=(this.config.max_month_events+1)*n);for(var c=0;c<_.length;c++)_[c].childNodes[1].style.height=h+"px";r[l]=(r[l-1]||0)+_[0].offsetHeight
}r[l]=(r[l-1]||0)+o.rows[l].cells[0].offsetHeight}r.unshift(0),o.parentNode.offsetHeight<o.parentNode.scrollHeight&&!o._h_fix}else if(i.length||"visible"!=this._els.dhx_multi_day[0].style.visibility||(r[0]=-1),i.length||-1==r[0]){var u=(o.parentNode.childNodes,(r[0]+1)*n+1+"px");d.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+parseInt(u,10)+"px",d.style.height=this._obj.offsetHeight-parseInt(d.style.top,10)-(this.xy.margin_top||0)+"px";var f=this._els.dhx_multi_day[0];
f.style.height=u,f.style.visibility=-1==r[0]?"hidden":"visible",f=this._els.dhx_multi_day[1],f.style.height=u,f.style.visibility=-1==r[0]?"hidden":"visible",f.className=r[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small",this._dy_shift=(r[0]+1)*n,r[0]=0}}return i};var i=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],s=function(t){for(var s=0,n=0;n<i.length;n++){var a=i[n],r=e._els[a]?e._els[a][0]:null,d=0;switch(a){case"dhx_cal_navline":case"dhx_cal_header":d=parseInt(r.style.height,10);
break;case"dhx_multi_day":d=r?r.offsetHeight:0,1==d&&(d=0);break;case"dhx_cal_data":d=Math.max(r.offsetHeight-1,r.scrollHeight);var o=e.getState().mode;if("month"==o){if(e.config.month_day_min_height&&!t){var l=r.getElementsByTagName("tr").length;d=l*e.config.month_day_min_height}t&&(r.style.height=d+"px")}if(e.matrix&&e.matrix[o])if(t)d+=2,r.style.height=d+"px";else{d=2;for(var _=e.matrix[o],h=_.y_unit,c=0;c<h.length;c++)d+=h[c].children?_.folder_dy||_.dy:_.dy}("day"==o||"week"==o)&&(d+=2)}s+=d}e._obj.style.height=s+"px",t||e.updateView()
},n=function(){var t=e.getState().mode;s(),(e.matrix&&e.matrix[t]||"month"==t)&&window.setTimeout(function(){s(!0)},1)};e.attachEvent("onViewChange",n),e.attachEvent("onXLE",n),e.attachEvent("onEventChanged",n),e.attachEvent("onEventCreated",n),e.attachEvent("onEventAdded",n),e.attachEvent("onEventDeleted",n),e.attachEvent("onAfterSchedulerResize",n),e.attachEvent("onClearAll",n)}()});