/*
dhtmlxScheduler.Net v.3.1.2 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.config.multisection=!0,scheduler.config.section_delemiter=",",scheduler.attachEvent("onSchedulerReady",function(){var e=scheduler._update_unit_section;scheduler._update_unit_section=function(t){return scheduler._update_sections(t,e)};var t=scheduler._update_timeline_section;scheduler._update_timeline_section=function(e){return scheduler._update_sections(e,t)},scheduler.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);return t.length>1
}return!1},scheduler._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a)},scheduler._parse_event_sections=function(e){return e instanceof Array?e:e.toString().split(scheduler.config.section_delemiter)},scheduler._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},scheduler._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];
a[t]||(a[t]=e)},scheduler._get_copied_event=function(e,t){if(!this._multisection_copies[e])return null;if(this._multisection_copies[e][t])return this._multisection_copies[e][t];var a=this._multisection_copies[e];if(scheduler._drag_event&&scheduler._drag_event._orig_section&&a[scheduler._drag_event._orig_section])return a[scheduler._drag_event._orig_section];var n=1/0,i=null;for(var s in a)a[s]._sorder<n&&(i=a[s],n=a[s]._sorder);return i},scheduler._clear_copied_events=function(){this._multisection_copies={}
},scheduler._clear_copied_events(),scheduler._split_events=function(e){var t=[],a=this._get_multisection_view(),n=this._get_section_property();if(a)for(var i=0;i<e.length;i++){var s=this._get_event_sections(e[i]);if(s.length>1){for(var r=0;r<s.length;r++)if("undefined"!=typeof a.order[s[r]]){var d=this._lame_copy({},e[i]);d[n]=s[r],t.push(d)}}else t.push(e[i])}else t=e;return t},scheduler._get_multisection_view=function(){return this.config.multisection?scheduler._get_section_view():!1};var a=scheduler.get_visible_events;
scheduler.get_visible_events=function(){this._clear_copied_events();{var e=a.apply(this,arguments);this._get_multisection_view()}return this._get_multisection_view()&&(e=this._split_events(e),this._register_copies_array(e)),e},scheduler._rendered_events={};var n=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),n.apply(this,[e,t])},scheduler._restore_render_flags=function(e){for(var t=this._get_section_property(),a=0;a<e.length;a++){var n=e[a],i=scheduler._get_copied_event(n.id,n[t]);
if(i)for(var s in i)0===s.indexOf("_")&&(n[s]=i[s])}},scheduler._update_sections=function(e,t){var a=e.view,n=e.event,i=e.pos;if(scheduler.isMultisectionEvent(n)){if(scheduler._drag_event._orig_section||(scheduler._drag_event._orig_section=i.section),scheduler._drag_event._orig_section!=i.section){var s=a.order[i.section]-a.order[scheduler._drag_event._orig_section];if(s){for(var r=this._get_event_sections(n),d=[],o=!0,_=0;_<r.length;_++){var l=scheduler._shift_sections(a,r[_],s);if(null===l){d=r,o=!1;
break}d[_]=l}o&&(scheduler._drag_event._orig_section=i.section),n[scheduler._get_section_property()]=d.join(",")}}}else t.apply(scheduler,[e])},scheduler._shift_sections=function(e,t,a){for(var n in e.order)if(e.order[n]-e.order[t]==a)return n;return null};var i=scheduler._get_blocked_zones;scheduler._get_blocked_zones=function(e,t,a,n,s){if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var r=[],d=0;d<t.length;d++)r=r.concat(i.apply(this,[e,t[d],a,n,s]));return r}return i.apply(this,arguments)
};var s=scheduler._check_sections_collision;scheduler._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,n=0,i=e.length;i>n&&!a;n++)for(var r=0,d=t.length;d>r;r++)if(s.apply(this,[e[n],t[r]])){a=!0;break}return a}return s.apply(this,arguments)}});