/*
dhtmlxScheduler.Net v.3.1.2 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){function t(e){return e.replace(E,"\n").replace(w,"")}function n(e,t){e=parseFloat(e),t=parseFloat(t),isNaN(t)||(e-=t);var n=i(e);return e=e-n.width+n.cols*y,isNaN(e)?"auto":100*e/y}function a(e,t,n){e=parseFloat(e),t=parseFloat(t),!isNaN(t)&&n&&(e-=t);var a=i(e);return e=e-a.width+a.cols*y,isNaN(e)?"auto":100*e/(y-(isNaN(t)?0:t))}function i(t){for(var n=0,a=e._els.dhx_cal_header[0].childNodes,i=a[1]?a[1].childNodes:a[0].childNodes,r=0;r<i.length;r++){var s=i[r].style?i[r]:i[r].parentNode,d=parseFloat(s.style.width);
if(!(t>d))break;t-=d+1,n+=d+1}return{width:n,cols:r}}function r(e){return e=parseFloat(e),isNaN(e)?"auto":100*e/b}function s(e,t){return(window.getComputedStyle?window.getComputedStyle(e,null)[t]:e.currentStyle?e.currentStyle[t]:null)||""}function d(t,n){for(var a=parseInt(t.style.left,10),i=0;i<e._cols.length;i++)if(a-=e._cols[i],0>a)return i;return n}function o(t,n){for(var a=parseInt(t.style.top,10),i=0;i<e._colsS.heights.length;i++)if(e._colsS.heights[i]>a)return i;return n}function l(e){return e?"<"+e+">":""
}function _(e){return e?"</"+e+">":""}function h(e,t,n,a){var i="<"+e+" profile='"+t+"'";return n&&(i+=" header='"+n+"'"),a&&(i+=" footer='"+a+"'"),i+=">"}function c(){var n="",a=e._mode;if(e.matrix&&e.matrix[e._mode]&&(a="cell"==e.matrix[e._mode].render?"matrix":"timeline"),n+="<scale mode='"+a+"' today='"+e._els.dhx_cal_date[0].innerHTML+"'>","week_agenda"==e._mode)for(var i=e._els.dhx_cal_data[0].getElementsByTagName("DIV"),r=0;r<i.length;r++)"dhx_wa_scale_bar"==i[r].className&&(n+="<column>"+t(i[r].innerHTML)+"</column>");
else if("agenda"==e._mode||"map"==e._mode){var i=e._els.dhx_cal_header[0].childNodes[0].childNodes;n+="<column>"+t(i[0].innerHTML)+"</column><column>"+t(i[1].innerHTML)+"</column>"}else if("year"==e._mode)for(var i=e._els.dhx_cal_data[0].childNodes,r=0;r<i.length;r++)n+="<month label='"+t(i[r].childNodes[0].innerHTML)+"'>",n+=f(i[r].childNodes[1].childNodes),n+=u(i[r].childNodes[2]),n+="</month>";else{n+="<x>";var i=e._els.dhx_cal_header[0].childNodes;n+=f(i),n+="</x>";var s=e._els.dhx_cal_data[0];
if(e.matrix&&e.matrix[e._mode]){n+="<y>";for(var r=0;r<s.firstChild.rows.length;r++){var d=s.firstChild.rows[r];n+="<row><![CDATA["+t(d.cells[0].innerHTML)+"]]></row>"}n+="</y>",b=s.firstChild.rows[0].cells[0].offsetHeight}else if("TABLE"==s.firstChild.tagName)n+=u(s);else{for(s=s.childNodes[s.childNodes.length-1];-1==s.className.indexOf("dhx_scale_holder");)s=s.previousSibling;s=s.childNodes,n+="<y>";for(var r=0;r<s.length;r++)n+="\n<row><![CDATA["+t(s[r].innerHTML)+"]]></row>";n+="</y>",b=s[0].offsetHeight
}}return n+="</scale>"}function u(e){for(var n="",a=e.firstChild.rows,i=0;i<a.length;i++){for(var r=[],s=0;s<a[i].cells.length;s++)r.push(a[i].cells[s].firstChild.innerHTML);n+="\n<row height='"+e.firstChild.rows[i].cells[0].offsetHeight+"'><![CDATA["+t(r.join("|"))+"]]></row>",b=e.firstChild.rows[0].cells[0].offsetHeight}return n}function f(n){var a,i="";e.matrix&&e.matrix[e._mode]&&(e.matrix[e._mode].second_scale&&(a=n[1].childNodes),n=n[0].childNodes);for(var r=0;r<n.length;r++)i+="\n<column><![CDATA["+t(n[r].innerHTML)+"]]></column>";
if(y=n[0].offsetWidth,a)for(var s=0,d=n[0].offsetWidth,o=1,r=0;r<a.length;r++)i+="\n<column second_scale='"+o+"'><![CDATA["+t(a[r].innerHTML)+"]]></column>",s+=a[r].offsetWidth,s>=d&&(d+=n[o]?n[o].offsetWidth:0,o++),y=a[0].offsetWidth;return i}function v(i){var l="",_=e._rendered,h=e.matrix&&e.matrix[e._mode];if("agenda"==e._mode||"map"==e._mode)for(var c=0;c<_.length;c++)l+="<event><head><![CDATA["+t(_[c].childNodes[0].innerHTML)+"]]></head><body><![CDATA["+t(_[c].childNodes[2].innerHTML)+"]]></body></event>";
else if("week_agenda"==e._mode)for(var c=0;c<_.length;c++)l+="<event day='"+_[c].parentNode.getAttribute("day")+"'><body>"+t(_[c].innerHTML)+"</body></event>";else if("year"==e._mode)for(var _=e.get_visible_events(),c=0;c<_.length;c++){var u=_[c].start_date;for(u.valueOf()<e._min_date.valueOf()&&(u=e._min_date);u<_[c].end_date;){var f=u.getMonth()+12*(u.getFullYear()-e._min_date.getFullYear())-e.week_starts._month,v=e.week_starts[f]+u.getDate()-1,g=i?s(e._get_year_cell(u),"color"):"",p=i?s(e._get_year_cell(u),"backgroundColor"):"";
if(l+="<event day='"+v%7+"' week='"+Math.floor(v/7)+"' month='"+f+"' backgroundColor='"+p+"' color='"+g+"'></event>",u=e.date.add(u,1,"day"),u.valueOf()>=e._max_date.valueOf())break}}else if(h&&"cell"==h.render)for(var _=e._els.dhx_cal_data[0].getElementsByTagName("TD"),c=0;c<_.length;c++){var g=i?s(_[c],"color"):"",p=i?s(_[c],"backgroundColor"):"";l+="\n<event><body backgroundColor='"+p+"' color='"+g+"'><![CDATA["+t(_[c].innerHTML)+"]]></body></event>"}else for(var c=0;c<_.length;c++){var m,x;if(e.matrix&&e.matrix[e._mode])m=n(_[c].style.left),x=n(_[c].offsetWidth)-1;
else{var y=e.config.use_select_menu_space?0:26;m=a(_[c].style.left,y,!0),x=a(_[c].style.width,y)-1}if(!isNaN(1*x)){var w=r(_[c].style.top),E=r(_[c].style.height),k=_[c].className.split(" ")[0].replace("dhx_cal_","");if("dhx_tooltip_line"!==k){var D=e.getEvent(_[c].getAttribute("event_id"));if(D){var v=D._sday,N=D._sweek,L=D._length||0;if("month"==e._mode)E=parseInt(_[c].offsetHeight,10),w=parseInt(_[c].style.top,10)-e.xy.month_head_height,v=d(_[c],v),N=o(_[c],N);else if(e.matrix&&e.matrix[e._mode]){v=0;
var M=_[c].parentNode.parentNode.parentNode;N=M.rowIndex;var C=b;b=_[c].parentNode.offsetHeight,w=r(_[c].style.top),w-=.2*w,b=C}else{if(_[c].parentNode==e._els.dhx_cal_data[0])continue;var O=e._els.dhx_cal_data[0].childNodes[0],T=parseFloat(-1!=O.className.indexOf("dhx_scale_holder")?O.style.left:0);m+=n(_[c].parentNode.style.left,T)}if(l+="\n<event week='"+N+"' day='"+v+"' type='"+k+"' x='"+m+"' y='"+w+"' width='"+x+"' height='"+E+"' len='"+L+"'>","event"==k){l+="<header><![CDATA["+t(_[c].childNodes[1].innerHTML)+"]]></header>";
var g=i?s(_[c].childNodes[2],"color"):"",p=i?s(_[c].childNodes[2],"backgroundColor"):"";l+="<body backgroundColor='"+p+"' color='"+g+"'><![CDATA["+t(_[c].childNodes[2].innerHTML)+"]]></body>"}else{var g=i?s(_[c],"color"):"",p=i?s(_[c],"backgroundColor"):"";l+="<body backgroundColor='"+p+"' color='"+g+"'><![CDATA["+t(_[c].innerHTML)+"]]></body>"}l+="</event>"}}}}return l}function g(t,n,a,i,r,s){var d=!1;"fullcolor"==i&&(d=!0,i="color"),i=i||"color";var o="";if(t){var u=e._date,f=e._mode;n=e.date[a+"_start"](n),n=e.date["get_"+a+"_end"]?e.date["get_"+a+"_end"](n):e.date.add(n,1,a),o=h("pages",i,r,s);
for(var g=new Date(t);+n>+g;g=this.date.add(g,1,a))this.setCurrentView(g,a),o+=l("page")+c().replace("–","-")+v(d)+_("page");o+=_("pages"),this.setCurrentView(u,f)}else o=h("data",i,r,s)+c().replace("–","-")+v(d)+_("data");return o}function p(t,n){var a=e.uid(),i=document.createElement("div");i.style.display="none",document.body.appendChild(i),i.innerHTML='<form id="'+a+'" method="post" target="_blank" action="'+n+'" accept-charset="utf-8" enctype="application/x-www-form-urlencoded"><input type="hidden" name="mycoolxmlbody"/> </form>',document.getElementById(a).firstChild.value=encodeURIComponent(t),document.getElementById(a).submit(),i.parentNode.removeChild(i)
}function m(e,t,n,a,i,r,s){var d="";d="object"==typeof i?x(i):g.apply(this,[e,t,n,i,r,s]),p(d,a)}function x(e){for(var t="<data>",n=0;n<e.length;n++)t+=e[n].source.getPDFData(e[n].start,e[n].end,e[n].view,e[n].mode,e[n].header,e[n].footer);return t+="</data>"}var y,b,w=new RegExp("<[^>]*>","g"),E=new RegExp("<br[^>]*>","g");e.getPDFData=g,e.toPDF=function(e,t,n,a){return m.apply(this,[null,null,null,e,t,n,a])},e.toPDFRange=function(t,n){return"string"==typeof t&&(t=e.templates.api_date(t),n=e.templates.api_date(n)),m.apply(this,arguments)
}}()});